package com.hyy.hyydatalist.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ALARMS.
 */
public class Alarms {

    private Long id;
    private String alarmtime;
    private String dayofweek;
    private String messageid;
    private String ispause;

    public Alarms() {
    }

    public Alarms(Long id) {
        this.id = id;
    }

    public Alarms(Long id, String alarmtime, String dayofweek, String messageid, String ispause) {
        this.id = id;
        this.alarmtime = alarmtime;
        this.dayofweek = dayofweek;
        this.messageid = messageid;
        this.ispause = ispause;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAlarmtime() {
        return alarmtime;
    }

    public void setAlarmtime(String alarmtime) {
        this.alarmtime = alarmtime;
    }

    public String getDayofweek() {
        return dayofweek;
    }

    public void setDayofweek(String dayofweek) {
        this.dayofweek = dayofweek;
    }

    public String getMessageid() {
        return messageid;
    }

    public void setMessageid(String messageid) {
        this.messageid = messageid;
    }

    public String getIspause() {
        return ispause;
    }

    public void setIspause(String ispause) {
        this.ispause = ispause;
    }

}
