package com.hyy.hyydatalist.generator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hyy.hyydatalist.generator.Messages;
import com.hyy.hyydatalist.generator.Alarms;

import com.hyy.hyydatalist.generator.MessagesDao;
import com.hyy.hyydatalist.generator.AlarmsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messagesDaoConfig;
    private final DaoConfig alarmsDaoConfig;

    private final MessagesDao messagesDao;
    private final AlarmsDao alarmsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        alarmsDaoConfig = daoConfigMap.get(AlarmsDao.class).clone();
        alarmsDaoConfig.initIdentityScope(type);

        messagesDao = new MessagesDao(messagesDaoConfig, this);
        alarmsDao = new AlarmsDao(alarmsDaoConfig, this);

        registerDao(Messages.class, messagesDao);
        registerDao(Alarms.class, alarmsDao);
    }
    
    public void clear() {
        messagesDaoConfig.getIdentityScope().clear();
        alarmsDaoConfig.getIdentityScope().clear();
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public AlarmsDao getAlarmsDao() {
        return alarmsDao;
    }

}
