package com.hyy.hyydatalist.generator;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MESSAGES.
 */
public class Messages {

    private Long id;
    private String title;
    private String shortcut;
    private String content;
    private String alarmstatus;

    // KEEP FIELDS - put your custom fields here
    private boolean isChecked;
    // KEEP FIELDS END

    public Messages() {
    }

    public Messages(Long id) {
        this.id = id;
    }

    public Messages(Long id, String title, String shortcut, String content, String alarmstatus) {
        this.id = id;
        this.title = title;
        this.shortcut = shortcut;
        this.content = content;
        this.alarmstatus = alarmstatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getShortcut() {
        return shortcut;
    }

    public void setShortcut(String shortcut) {
        this.shortcut = shortcut;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAlarmstatus() {
        return alarmstatus;
    }

    public void setAlarmstatus(String alarmstatus) {
        this.alarmstatus = alarmstatus;
    }

    // KEEP METHODS - put your custom methods here
    public void setIsChecked(boolean ischecked){
    	this.isChecked = ischecked;
    }
    
    public boolean getIsChecked(){
    	return this.isChecked;
    }
    // KEEP METHODS END

}
